PROGRAMS    = vdtest
vdtest_LDFLAGS = -L/usr/local/4psa_framework/2.0.5/lib
vdtest_LIBS = 4psa_base
     
CFLAGS+=-I./include -DLINUX -Wall -I/usr/local/4psa_framework/2.0.5/include

vdtest_OBJS = vdtest.o vdnet.o
vdtest_CFLAGS = -ggdb3 $(CFLAGS)

DEVELOPER_MODE=1
COLOURED_OUTPUT=1
SILENT_BUILD=1

include Makefile.rules

